#region Common Public License Copyright Notice
/**************************************************************************\
* Neumont Object-Role Modeling Architect for Visual Studio                 *
*                                                                          *
* Copyright © Neumont University. All rights reserved.                     *
*                                                                          *
* The use and distribution terms for this software are covered by the      *
* Common Public License 1.0 (http://opensource.org/licenses/cpl) which     *
* can be found in the file CPL.txt at the root of this distribution.       *
* By using this software in any fashion, you are agreeing to be bound by   *
* the terms of this license.                                               *
*                                                                          *
* You must not remove this notice, or any other, from this software.       *
\**************************************************************************/
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace Neumont.Tools.ORMToORMAbstractionBridge
{
	/// <summary>
	/// DomainRelationship FactTypeMapsTowardsRole
	/// Description for Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole
	/// </summary>
	[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("98abb729-f2f0-4629-bfa7-801b6615137d")]
	public partial class FactTypeMapsTowardsRole : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// FactTypeMapsTowardsRole domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x98abb729, 0xf2f0, 0x4629, 0xbf, 0xa7, 0x80, 0x1b, 0x66, 0x15, 0x13, 0x7d);
	
				
		/// <summary>
		/// Constructor
		/// Creates a FactTypeMapsTowardsRole link in the same Partition as the given FactType
		/// </summary>
		/// <param name="source">FactType to use as the source of the relationship.</param>
		/// <param name="target">RoleBase to use as the target of the relationship.</param>
		public FactTypeMapsTowardsRole(global::Neumont.Tools.ORM.ObjectModel.FactType source, global::Neumont.Tools.ORM.ObjectModel.RoleBase target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(FactTypeMapsTowardsRole.FactTypeDomainRoleId, source), new DslModeling::RoleAssignment(FactTypeMapsTowardsRole.TowardsRoleDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public FactTypeMapsTowardsRole(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public FactTypeMapsTowardsRole(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public FactTypeMapsTowardsRole(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public FactTypeMapsTowardsRole(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region FactType domain role code
		
		/// <summary>
		/// FactType domain role Id.
		/// </summary>
		public static readonly global::System.Guid FactTypeDomainRoleId = new global::System.Guid(0x05abb37c, 0x0363, 0x4bd5, 0xbe, 0x02, 0xf6, 0x88, 0xbf, 0xdb, 0x55, 0xa5);
		
		/// <summary>
		/// DomainRole FactType
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.FactType
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/FactType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/FactType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "TowardsRole", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/FactType.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("05abb37c-0363-4bd5-be02-f688bfdb55a5")]
		public virtual global::Neumont.Tools.ORM.ObjectModel.FactType FactType
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORM.ObjectModel.FactType)DslModeling::DomainRoleInfo.GetRolePlayer(this, FactTypeDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, FactTypeDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access FactType of a RoleBase
		/// <summary>
		/// Gets FactType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORM.ObjectModel.FactType GetFactType(global::Neumont.Tools.ORM.ObjectModel.RoleBase element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, TowardsRoleDomainRoleId) as global::Neumont.Tools.ORM.ObjectModel.FactType;
		}
		
		/// <summary>
		/// Sets FactType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetFactType(global::Neumont.Tools.ORM.ObjectModel.RoleBase element, global::Neumont.Tools.ORM.ObjectModel.FactType newFactType)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, TowardsRoleDomainRoleId, newFactType);
		}
		#endregion
		#region TowardsRole domain role code
		
		/// <summary>
		/// TowardsRole domain role Id.
		/// </summary>
		public static readonly global::System.Guid TowardsRoleDomainRoleId = new global::System.Guid(0x89ebc0d2, 0x380d, 0x4434, 0x9e, 0x1e, 0xf5, 0xe9, 0xc6, 0xb7, 0xeb, 0x16);
		
		/// <summary>
		/// DomainRole TowardsRole
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.TowardsRole
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/TowardsRole.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/TowardsRole.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "FactType", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/TowardsRole.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("89ebc0d2-380d-4434-9e1e-f5e9c6b7eb16")]
		public virtual global::Neumont.Tools.ORM.ObjectModel.RoleBase TowardsRole
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORM.ObjectModel.RoleBase)DslModeling::DomainRoleInfo.GetRolePlayer(this, TowardsRoleDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TowardsRoleDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access TowardsRole of a FactType
		/// <summary>
		/// Gets TowardsRole.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORM.ObjectModel.RoleBase GetTowardsRole(global::Neumont.Tools.ORM.ObjectModel.FactType element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, FactTypeDomainRoleId) as global::Neumont.Tools.ORM.ObjectModel.RoleBase;
		}
		
		/// <summary>
		/// Sets TowardsRole.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetTowardsRole(global::Neumont.Tools.ORM.ObjectModel.FactType element, global::Neumont.Tools.ORM.ObjectModel.RoleBase newTowardsRole)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, FactTypeDomainRoleId, newTowardsRole);
		}
		#endregion
		#region Depth domain property code
		
		/// <summary>
		/// Depth domain property Id.
		/// </summary>
		public static readonly global::System.Guid DepthDomainPropertyId = new global::System.Guid(0x720b9285, 0xcc59, 0x48e2, 0x8b, 0x33, 0xd9, 0x94, 0x4a, 0x9e, 0xd4, 0x00);
		
		/// <summary>
		/// Storage for Depth
		/// </summary>
		private MappingDepth depthPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of Depth domain property.
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.Depth
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/Depth.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole/Depth.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainObjectId("720b9285-cc59-48e2-8b33-d9944a9ed400")]
		public MappingDepth Depth
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return depthPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DepthPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the FactTypeMapsTowardsRole.Depth domain property.
		/// </summary>
		internal sealed partial class DepthPropertyHandler : DslModeling::DomainPropertyValueHandler<FactTypeMapsTowardsRole, MappingDepth>
		{
			private DepthPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the FactTypeMapsTowardsRole.Depth domain property value handler.
			/// </summary>
			public static readonly DepthPropertyHandler Instance = new DepthPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the FactTypeMapsTowardsRole.Depth domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DepthDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed MappingDepth GetValue(FactTypeMapsTowardsRole element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.depthPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(FactTypeMapsTowardsRole element, MappingDepth newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				MappingDepth oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.depthPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region FactType link accessor
		/// <summary>
		/// Get the FactTypeMapsTowardsRole link to a FactType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole GetLinkToTowardsRole (global::Neumont.Tools.ORM.ObjectModel.FactType factTypeInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole>(factTypeInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.FactTypeDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of FactType not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region TowardsRole link accessor
		/// <summary>
		/// Get the FactTypeMapsTowardsRole link to a RoleBase.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole GetLinkToFactType (global::Neumont.Tools.ORM.ObjectModel.RoleBase towardsRoleInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole>(towardsRoleInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.TowardsRoleDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of TowardsRole not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region FactTypeMapsTowardsRole instance accessors
		
		/// <summary>
		/// Get any FactTypeMapsTowardsRole links between a given FactType and a RoleBase.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole> GetLinks( global::Neumont.Tools.ORM.ObjectModel.FactType source, global::Neumont.Tools.ORM.ObjectModel.RoleBase target )
		{
			global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole> outLinks = new global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole>();
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.FactTypeDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole link in links )
			{
				if ( target.Equals(link.TowardsRole) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one FactTypeMapsTowardsRole link between a given FactTypeand a RoleBase.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole GetLink( global::Neumont.Tools.ORM.ObjectModel.FactType source, global::Neumont.Tools.ORM.ObjectModel.RoleBase target )
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole.FactTypeDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.FactTypeMapsTowardsRole link in links )
			{
				if ( target.Equals(link.TowardsRole) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Neumont.Tools.ORMToORMAbstractionBridge
{
	/// <summary>
	/// DomainRelationship AbstractionModelIsForORMModel
	/// Description for
	/// Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel
	/// </summary>
	[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("02969205-dc37-4d83-acf2-506a6a3fe02c")]
	public partial class AbstractionModelIsForORMModel : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// AbstractionModelIsForORMModel domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x02969205, 0xdc37, 0x4d83, 0xac, 0xf2, 0x50, 0x6a, 0x6a, 0x3f, 0xe0, 0x2c);
	
				
		/// <summary>
		/// Constructor
		/// Creates a AbstractionModelIsForORMModel link in the same Partition as the given AbstractionModel
		/// </summary>
		/// <param name="source">AbstractionModel to use as the source of the relationship.</param>
		/// <param name="target">ORMModel to use as the target of the relationship.</param>
		public AbstractionModelIsForORMModel(global::Neumont.Tools.ORMAbstraction.AbstractionModel source, global::Neumont.Tools.ORM.ObjectModel.ORMModel target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(AbstractionModelIsForORMModel.AbstractionModelDomainRoleId, source), new DslModeling::RoleAssignment(AbstractionModelIsForORMModel.ORMModelDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public AbstractionModelIsForORMModel(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public AbstractionModelIsForORMModel(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public AbstractionModelIsForORMModel(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public AbstractionModelIsForORMModel(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region AbstractionModel domain role code
		
		/// <summary>
		/// AbstractionModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid AbstractionModelDomainRoleId = new global::System.Guid(0xfdb675b5, 0xbfe3, 0x4c5c, 0x8b, 0x22, 0xc5, 0xcf, 0xb0, 0x33, 0x38, 0x11);
		
		/// <summary>
		/// DomainRole AbstractionModel
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.AbstractionModel
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel/AbstractionModel.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel/AbstractionModel.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "ORMModel", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel/AbstractionModel.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("fdb675b5-bfe3-4c5c-8b22-c5cfb0333811")]
		public virtual global::Neumont.Tools.ORMAbstraction.AbstractionModel AbstractionModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORMAbstraction.AbstractionModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, AbstractionModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AbstractionModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AbstractionModel of a ORMModel
		/// <summary>
		/// Gets AbstractionModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMAbstraction.AbstractionModel GetAbstractionModel(global::Neumont.Tools.ORM.ObjectModel.ORMModel element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ORMModelDomainRoleId) as global::Neumont.Tools.ORMAbstraction.AbstractionModel;
		}
		
		/// <summary>
		/// Sets AbstractionModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetAbstractionModel(global::Neumont.Tools.ORM.ObjectModel.ORMModel element, global::Neumont.Tools.ORMAbstraction.AbstractionModel newAbstractionModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ORMModelDomainRoleId, newAbstractionModel);
		}
		#endregion
		#region ORMModel domain role code
		
		/// <summary>
		/// ORMModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid ORMModelDomainRoleId = new global::System.Guid(0x5021fd0a, 0xc82f, 0x4319, 0xac, 0x52, 0xf9, 0x9b, 0xdf, 0x7b, 0x98, 0x82);
		
		/// <summary>
		/// DomainRole ORMModel
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.ORMModel
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel/ORMModel.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel/ORMModel.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "AbstractionModel", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel/ORMModel.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("5021fd0a-c82f-4319-ac52-f99bdf7b9882")]
		public virtual global::Neumont.Tools.ORM.ObjectModel.ORMModel ORMModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORM.ObjectModel.ORMModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, ORMModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ORMModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ORMModel of a AbstractionModel
		/// <summary>
		/// Gets ORMModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORM.ObjectModel.ORMModel GetORMModel(global::Neumont.Tools.ORMAbstraction.AbstractionModel element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AbstractionModelDomainRoleId) as global::Neumont.Tools.ORM.ObjectModel.ORMModel;
		}
		
		/// <summary>
		/// Sets ORMModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetORMModel(global::Neumont.Tools.ORMAbstraction.AbstractionModel element, global::Neumont.Tools.ORM.ObjectModel.ORMModel newORMModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AbstractionModelDomainRoleId, newORMModel);
		}
		#endregion
		#region AbstractionModel link accessor
		/// <summary>
		/// Get the AbstractionModelIsForORMModel link to a AbstractionModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel GetLinkToORMModel (global::Neumont.Tools.ORMAbstraction.AbstractionModel abstractionModelInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel>(abstractionModelInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.AbstractionModelDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AbstractionModel not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ORMModel link accessor
		/// <summary>
		/// Get the AbstractionModelIsForORMModel link to a ORMModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel GetLinkToAbstractionModel (global::Neumont.Tools.ORM.ObjectModel.ORMModel oRMModelInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel>(oRMModelInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.ORMModelDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of ORMModel not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region AbstractionModelIsForORMModel instance accessors
		
		/// <summary>
		/// Get any AbstractionModelIsForORMModel links between a given AbstractionModel and a ORMModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel> GetLinks( global::Neumont.Tools.ORMAbstraction.AbstractionModel source, global::Neumont.Tools.ORM.ObjectModel.ORMModel target )
		{
			global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel> outLinks = new global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel>();
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.AbstractionModelDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel link in links )
			{
				if ( target.Equals(link.ORMModel) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one AbstractionModelIsForORMModel link between a given AbstractionModeland a ORMModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel GetLink( global::Neumont.Tools.ORMAbstraction.AbstractionModel source, global::Neumont.Tools.ORM.ObjectModel.ORMModel target )
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel.AbstractionModelDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.AbstractionModelIsForORMModel link in links )
			{
				if ( target.Equals(link.ORMModel) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Neumont.Tools.ORMToORMAbstractionBridge
{
	/// <summary>
	/// DomainRelationship ConceptTypeIsForObjectType
	/// Description for
	/// Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType
	/// </summary>
	[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("494ee309-435b-4dd1-b2dd-c7e794f768db")]
	public partial class ConceptTypeIsForObjectType : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ConceptTypeIsForObjectType domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x494ee309, 0x435b, 0x4dd1, 0xb2, 0xdd, 0xc7, 0xe7, 0x94, 0xf7, 0x68, 0xdb);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ConceptTypeIsForObjectType link in the same Partition as the given ConceptType
		/// </summary>
		/// <param name="source">ConceptType to use as the source of the relationship.</param>
		/// <param name="target">ObjectType to use as the target of the relationship.</param>
		public ConceptTypeIsForObjectType(global::Neumont.Tools.ORMAbstraction.ConceptType source, global::Neumont.Tools.ORM.ObjectModel.ObjectType target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ConceptTypeIsForObjectType.ConceptTypeDomainRoleId, source), new DslModeling::RoleAssignment(ConceptTypeIsForObjectType.ObjectTypeDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ConceptTypeIsForObjectType(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ConceptTypeIsForObjectType(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ConceptTypeIsForObjectType(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ConceptTypeIsForObjectType(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region ConceptType domain role code
		
		/// <summary>
		/// ConceptType domain role Id.
		/// </summary>
		public static readonly global::System.Guid ConceptTypeDomainRoleId = new global::System.Guid(0xee5f768c, 0xb308, 0x480e, 0xa4, 0x44, 0xf8, 0x6f, 0x81, 0xb0, 0x2f, 0x46);
		
		/// <summary>
		/// DomainRole ConceptType
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.ConceptType
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType/ConceptType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType/ConceptType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "ObjectType", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType/ConceptType.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("ee5f768c-b308-480e-a444-f86f81b02f46")]
		public virtual global::Neumont.Tools.ORMAbstraction.ConceptType ConceptType
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORMAbstraction.ConceptType)DslModeling::DomainRoleInfo.GetRolePlayer(this, ConceptTypeDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ConceptTypeDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ConceptType of a ObjectType
		/// <summary>
		/// Gets ConceptType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMAbstraction.ConceptType GetConceptType(global::Neumont.Tools.ORM.ObjectModel.ObjectType element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ObjectTypeDomainRoleId) as global::Neumont.Tools.ORMAbstraction.ConceptType;
		}
		
		/// <summary>
		/// Sets ConceptType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetConceptType(global::Neumont.Tools.ORM.ObjectModel.ObjectType element, global::Neumont.Tools.ORMAbstraction.ConceptType newConceptType)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ObjectTypeDomainRoleId, newConceptType);
		}
		#endregion
		#region ObjectType domain role code
		
		/// <summary>
		/// ObjectType domain role Id.
		/// </summary>
		public static readonly global::System.Guid ObjectTypeDomainRoleId = new global::System.Guid(0x02c44e70, 0xf770, 0x42a3, 0x80, 0xe8, 0xc2, 0x33, 0x9a, 0x49, 0x68, 0x7c);
		
		/// <summary>
		/// DomainRole ObjectType
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.ObjectType
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType/ObjectType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType/ObjectType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "ConceptType", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType/ObjectType.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("02c44e70-f770-42a3-80e8-c2339a49687c")]
		public virtual global::Neumont.Tools.ORM.ObjectModel.ObjectType ObjectType
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORM.ObjectModel.ObjectType)DslModeling::DomainRoleInfo.GetRolePlayer(this, ObjectTypeDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ObjectTypeDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ObjectType of a ConceptType
		/// <summary>
		/// Gets ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORM.ObjectModel.ObjectType GetObjectType(global::Neumont.Tools.ORMAbstraction.ConceptType element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ConceptTypeDomainRoleId) as global::Neumont.Tools.ORM.ObjectModel.ObjectType;
		}
		
		/// <summary>
		/// Sets ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetObjectType(global::Neumont.Tools.ORMAbstraction.ConceptType element, global::Neumont.Tools.ORM.ObjectModel.ObjectType newObjectType)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ConceptTypeDomainRoleId, newObjectType);
		}
		#endregion
		#region ConceptType link accessor
		/// <summary>
		/// Get the ConceptTypeIsForObjectType link to a ConceptType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType GetLinkToObjectType (global::Neumont.Tools.ORMAbstraction.ConceptType conceptTypeInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType>(conceptTypeInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.ConceptTypeDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of ConceptType not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ObjectType link accessor
		/// <summary>
		/// Get the ConceptTypeIsForObjectType link to a ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType GetLinkToConceptType (global::Neumont.Tools.ORM.ObjectModel.ObjectType objectTypeInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType>(objectTypeInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.ObjectTypeDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of ObjectType not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ConceptTypeIsForObjectType instance accessors
		
		/// <summary>
		/// Get any ConceptTypeIsForObjectType links between a given ConceptType and a ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType> GetLinks( global::Neumont.Tools.ORMAbstraction.ConceptType source, global::Neumont.Tools.ORM.ObjectModel.ObjectType target )
		{
			global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType> outLinks = new global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType>();
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.ConceptTypeDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType link in links )
			{
				if ( target.Equals(link.ObjectType) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ConceptTypeIsForObjectType link between a given ConceptTypeand a ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType GetLink( global::Neumont.Tools.ORMAbstraction.ConceptType source, global::Neumont.Tools.ORM.ObjectModel.ObjectType target )
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType.ConceptTypeDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeIsForObjectType link in links )
			{
				if ( target.Equals(link.ObjectType) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Neumont.Tools.ORMToORMAbstractionBridge
{
	/// <summary>
	/// DomainRelationship ConceptTypeChildHasPathFactType
	/// Description for
	/// Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType
	/// </summary>
	[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("a7d4ff78-1217-41c4-9c63-559ffbf2af4b")]
	public partial class ConceptTypeChildHasPathFactType : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ConceptTypeChildHasPathFactType domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xa7d4ff78, 0x1217, 0x41c4, 0x9c, 0x63, 0x55, 0x9f, 0xfb, 0xf2, 0xaf, 0x4b);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ConceptTypeChildHasPathFactType link in the same Partition as the given ConceptTypeChild
		/// </summary>
		/// <param name="source">ConceptTypeChild to use as the source of the relationship.</param>
		/// <param name="target">FactType to use as the target of the relationship.</param>
		public ConceptTypeChildHasPathFactType(global::Neumont.Tools.ORMAbstraction.ConceptTypeChild source, global::Neumont.Tools.ORM.ObjectModel.FactType target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ConceptTypeChildHasPathFactType.ConceptTypeChildDomainRoleId, source), new DslModeling::RoleAssignment(ConceptTypeChildHasPathFactType.PathFactTypeDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ConceptTypeChildHasPathFactType(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ConceptTypeChildHasPathFactType(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ConceptTypeChildHasPathFactType(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ConceptTypeChildHasPathFactType(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region ConceptTypeChild domain role code
		
		/// <summary>
		/// ConceptTypeChild domain role Id.
		/// </summary>
		public static readonly global::System.Guid ConceptTypeChildDomainRoleId = new global::System.Guid(0x309ecb8e, 0x8840, 0x48fb, 0x95, 0x91, 0xef, 0x74, 0xcc, 0x1b, 0x80, 0x5c);
		
		/// <summary>
		/// DomainRole ConceptTypeChild
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.ConceptTypeChild
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType/ConceptTypeChild.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType/ConceptTypeChild.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "PathFactTypeCollection", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType/ConceptTypeChild.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.OneMany)]
		[DslModeling::DomainObjectId("309ecb8e-8840-48fb-9591-ef74cc1b805c")]
		public virtual global::Neumont.Tools.ORMAbstraction.ConceptTypeChild ConceptTypeChild
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORMAbstraction.ConceptTypeChild)DslModeling::DomainRoleInfo.GetRolePlayer(this, ConceptTypeChildDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ConceptTypeChildDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ConceptTypeChild of a FactType
		/// <summary>
		/// Gets a list of ConceptTypeChild.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<global::Neumont.Tools.ORMAbstraction.ConceptTypeChild> GetConceptTypeChild(global::Neumont.Tools.ORM.ObjectModel.FactType element)
		{
			return new DslModeling::LinkedElementCollection<global::Neumont.Tools.ORMAbstraction.ConceptTypeChild>(element, PathFactTypeDomainRoleId);
		}
		#endregion
		#region PathFactType domain role code
		
		/// <summary>
		/// PathFactType domain role Id.
		/// </summary>
		public static readonly global::System.Guid PathFactTypeDomainRoleId = new global::System.Guid(0xa8ead929, 0xe0a5, 0x4dc3, 0x82, 0x84, 0x08, 0x13, 0x17, 0x3b, 0xe9, 0x08);
		
		/// <summary>
		/// DomainRole PathFactType
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.PathFactType
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType/PathFactType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType/PathFactType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "ConceptTypeChild", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType/PathFactType.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("a8ead929-e0a5-4dc3-8284-0813173be908")]
		public virtual global::Neumont.Tools.ORM.ObjectModel.FactType PathFactType
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORM.ObjectModel.FactType)DslModeling::DomainRoleInfo.GetRolePlayer(this, PathFactTypeDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, PathFactTypeDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access PathFactTypeCollection of a ConceptTypeChild
		/// <summary>
		/// Gets a list of PathFactTypeCollection.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<global::Neumont.Tools.ORM.ObjectModel.FactType> GetPathFactTypeCollection(global::Neumont.Tools.ORMAbstraction.ConceptTypeChild element)
		{
			return new DslModeling::LinkedElementCollection<global::Neumont.Tools.ORM.ObjectModel.FactType>(element, ConceptTypeChildDomainRoleId);
		}
		#endregion
		#region ConceptTypeChild link accessor
		/// <summary>
		/// Get the list of ConceptTypeChildHasPathFactType links to a ConceptTypeChild.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType> GetLinksToPathFactTypeCollection ( global::Neumont.Tools.ORMAbstraction.ConceptTypeChild conceptTypeChildInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType>(conceptTypeChildInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.ConceptTypeChildDomainRoleId);
		}
		#endregion
		#region PathFactType link accessor
		/// <summary>
		/// Get the list of ConceptTypeChildHasPathFactType links to a FactType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType> GetLinksToConceptTypeChild ( global::Neumont.Tools.ORM.ObjectModel.FactType pathFactTypeInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType>(pathFactTypeInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.PathFactTypeDomainRoleId);
		}
		#endregion
		#region ConceptTypeChildHasPathFactType instance accessors
		
		/// <summary>
		/// Get any ConceptTypeChildHasPathFactType links between a given ConceptTypeChild and a FactType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType> GetLinks( global::Neumont.Tools.ORMAbstraction.ConceptTypeChild source, global::Neumont.Tools.ORM.ObjectModel.FactType target )
		{
			global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType> outLinks = new global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType>();
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.ConceptTypeChildDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType link in links )
			{
				if ( target.Equals(link.PathFactType) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ConceptTypeChildHasPathFactType link between a given ConceptTypeChildand a FactType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType GetLink( global::Neumont.Tools.ORMAbstraction.ConceptTypeChild source, global::Neumont.Tools.ORM.ObjectModel.FactType target )
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType.ConceptTypeChildDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.ConceptTypeChildHasPathFactType link in links )
			{
				if ( target.Equals(link.PathFactType) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Neumont.Tools.ORMToORMAbstractionBridge
{
	/// <summary>
	/// DomainRelationship InformationTypeFormatIsForValueType
	/// Description for
	/// Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType
	/// </summary>
	[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("fb9fcda4-030c-4f2f-8201-5287f79c25af")]
	public partial class InformationTypeFormatIsForValueType : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// InformationTypeFormatIsForValueType domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xfb9fcda4, 0x030c, 0x4f2f, 0x82, 0x01, 0x52, 0x87, 0xf7, 0x9c, 0x25, 0xaf);
	
				
		/// <summary>
		/// Constructor
		/// Creates a InformationTypeFormatIsForValueType link in the same Partition as the given InformationTypeFormat
		/// </summary>
		/// <param name="source">InformationTypeFormat to use as the source of the relationship.</param>
		/// <param name="target">ObjectType to use as the target of the relationship.</param>
		public InformationTypeFormatIsForValueType(global::Neumont.Tools.ORMAbstraction.InformationTypeFormat source, global::Neumont.Tools.ORM.ObjectModel.ObjectType target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(InformationTypeFormatIsForValueType.InformationTypeFormatDomainRoleId, source), new DslModeling::RoleAssignment(InformationTypeFormatIsForValueType.ValueTypeDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public InformationTypeFormatIsForValueType(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public InformationTypeFormatIsForValueType(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public InformationTypeFormatIsForValueType(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public InformationTypeFormatIsForValueType(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region InformationTypeFormat domain role code
		
		/// <summary>
		/// InformationTypeFormat domain role Id.
		/// </summary>
		public static readonly global::System.Guid InformationTypeFormatDomainRoleId = new global::System.Guid(0xe7453c11, 0x962f, 0x4d37, 0x9e, 0x69, 0xf0, 0x1e, 0x83, 0x81, 0x0c, 0xc8);
		
		/// <summary>
		/// DomainRole InformationTypeFormat
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.InformationTypeFormat
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType/InformationTypeFormat.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType/InformationTypeFormat.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "ValueType", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType/InformationTypeFormat.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("e7453c11-962f-4d37-9e69-f01e83810cc8")]
		public virtual global::Neumont.Tools.ORMAbstraction.InformationTypeFormat InformationTypeFormat
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORMAbstraction.InformationTypeFormat)DslModeling::DomainRoleInfo.GetRolePlayer(this, InformationTypeFormatDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, InformationTypeFormatDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access InformationTypeFormat of a ObjectType
		/// <summary>
		/// Gets InformationTypeFormat.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMAbstraction.InformationTypeFormat GetInformationTypeFormat(global::Neumont.Tools.ORM.ObjectModel.ObjectType element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ValueTypeDomainRoleId) as global::Neumont.Tools.ORMAbstraction.InformationTypeFormat;
		}
		
		/// <summary>
		/// Sets InformationTypeFormat.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetInformationTypeFormat(global::Neumont.Tools.ORM.ObjectModel.ObjectType element, global::Neumont.Tools.ORMAbstraction.InformationTypeFormat newInformationTypeFormat)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ValueTypeDomainRoleId, newInformationTypeFormat);
		}
		#endregion
		#region ValueType domain role code
		
		/// <summary>
		/// ValueType domain role Id.
		/// </summary>
		public static readonly global::System.Guid ValueTypeDomainRoleId = new global::System.Guid(0xee9cf583, 0xcd1b, 0x4df1, 0xba, 0xfb, 0xc4, 0xc2, 0x20, 0xb6, 0xd6, 0x85);
		
		/// <summary>
		/// DomainRole ValueType
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.ValueType
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType/ValueType.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType/ValueType.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "InformationTypeFormat", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType/ValueType.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("ee9cf583-cd1b-4df1-bafb-c4c220b6d685")]
		public virtual global::Neumont.Tools.ORM.ObjectModel.ObjectType ValueType
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORM.ObjectModel.ObjectType)DslModeling::DomainRoleInfo.GetRolePlayer(this, ValueTypeDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ValueTypeDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ValueType of a InformationTypeFormat
		/// <summary>
		/// Gets ValueType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORM.ObjectModel.ObjectType GetValueType(global::Neumont.Tools.ORMAbstraction.InformationTypeFormat element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, InformationTypeFormatDomainRoleId) as global::Neumont.Tools.ORM.ObjectModel.ObjectType;
		}
		
		/// <summary>
		/// Sets ValueType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetValueType(global::Neumont.Tools.ORMAbstraction.InformationTypeFormat element, global::Neumont.Tools.ORM.ObjectModel.ObjectType newValueType)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, InformationTypeFormatDomainRoleId, newValueType);
		}
		#endregion
		#region InformationTypeFormat link accessor
		/// <summary>
		/// Get the InformationTypeFormatIsForValueType link to a InformationTypeFormat.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType GetLinkToValueType (global::Neumont.Tools.ORMAbstraction.InformationTypeFormat informationTypeFormatInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType>(informationTypeFormatInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.InformationTypeFormatDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of InformationTypeFormat not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ValueType link accessor
		/// <summary>
		/// Get the InformationTypeFormatIsForValueType link to a ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType GetLinkToInformationTypeFormat (global::Neumont.Tools.ORM.ObjectModel.ObjectType valueTypeInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType>(valueTypeInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.ValueTypeDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of ValueType not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region InformationTypeFormatIsForValueType instance accessors
		
		/// <summary>
		/// Get any InformationTypeFormatIsForValueType links between a given InformationTypeFormat and a ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType> GetLinks( global::Neumont.Tools.ORMAbstraction.InformationTypeFormat source, global::Neumont.Tools.ORM.ObjectModel.ObjectType target )
		{
			global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType> outLinks = new global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType>();
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.InformationTypeFormatDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType link in links )
			{
				if ( target.Equals(link.ValueType) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one InformationTypeFormatIsForValueType link between a given InformationTypeFormatand a ObjectType.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType GetLink( global::Neumont.Tools.ORMAbstraction.InformationTypeFormat source, global::Neumont.Tools.ORM.ObjectModel.ObjectType target )
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType.InformationTypeFormatDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.InformationTypeFormatIsForValueType link in links )
			{
				if ( target.Equals(link.ValueType) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Neumont.Tools.ORMToORMAbstractionBridge
{
	/// <summary>
	/// DomainRelationship UniquenessIsForUniquenessConstraint
	/// Description for
	/// Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint
	/// </summary>
	[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("e61822c1-04ee-4ae3-a28e-f45879c8fe41")]
	public partial class UniquenessIsForUniquenessConstraint : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// UniquenessIsForUniquenessConstraint domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe61822c1, 0x04ee, 0x4ae3, 0xa2, 0x8e, 0xf4, 0x58, 0x79, 0xc8, 0xfe, 0x41);
	
				
		/// <summary>
		/// Constructor
		/// Creates a UniquenessIsForUniquenessConstraint link in the same Partition as the given Uniqueness
		/// </summary>
		/// <param name="source">Uniqueness to use as the source of the relationship.</param>
		/// <param name="target">UniquenessConstraint to use as the target of the relationship.</param>
		public UniquenessIsForUniquenessConstraint(global::Neumont.Tools.ORMAbstraction.Uniqueness source, global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(UniquenessIsForUniquenessConstraint.UniquenessDomainRoleId, source), new DslModeling::RoleAssignment(UniquenessIsForUniquenessConstraint.UniquenessConstraintDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public UniquenessIsForUniquenessConstraint(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public UniquenessIsForUniquenessConstraint(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartition : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public UniquenessIsForUniquenessConstraint(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public UniquenessIsForUniquenessConstraint(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Uniqueness domain role code
		
		/// <summary>
		/// Uniqueness domain role Id.
		/// </summary>
		public static readonly global::System.Guid UniquenessDomainRoleId = new global::System.Guid(0x4c49f284, 0x81c1, 0x41e8, 0x8a, 0x23, 0x13, 0x7d, 0xef, 0x1d, 0x22, 0x9f);
		
		/// <summary>
		/// DomainRole Uniqueness
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.Uniqueness
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint/Uniqueness.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint/Uniqueness.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "UniquenessConstraint", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint/Uniqueness.PropertyDisplayName", PropagatesDelete = true, Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("4c49f284-81c1-41e8-8a23-137def1d229f")]
		public virtual global::Neumont.Tools.ORMAbstraction.Uniqueness Uniqueness
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORMAbstraction.Uniqueness)DslModeling::DomainRoleInfo.GetRolePlayer(this, UniquenessDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, UniquenessDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Uniqueness of a UniquenessConstraint
		/// <summary>
		/// Gets Uniqueness.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMAbstraction.Uniqueness GetUniqueness(global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, UniquenessConstraintDomainRoleId) as global::Neumont.Tools.ORMAbstraction.Uniqueness;
		}
		
		/// <summary>
		/// Sets Uniqueness.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetUniqueness(global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint element, global::Neumont.Tools.ORMAbstraction.Uniqueness newUniqueness)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, UniquenessConstraintDomainRoleId, newUniqueness);
		}
		#endregion
		#region UniquenessConstraint domain role code
		
		/// <summary>
		/// UniquenessConstraint domain role Id.
		/// </summary>
		public static readonly global::System.Guid UniquenessConstraintDomainRoleId = new global::System.Guid(0x6d7dd635, 0x6b8d, 0x4ea7, 0xa2, 0xa5, 0x00, 0x3a, 0xda, 0x32, 0xaf, 0xd0);
		
		/// <summary>
		/// DomainRole UniquenessConstraint
		/// Description for
		/// Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.UniquenessConstraint
		/// </summary>
		[DslDesign::DisplayNameResource("Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint/UniquenessConstraint.DisplayName", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslDesign::DescriptionResource("Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint/UniquenessConstraint.Description", typeof(global::Neumont.Tools.ORMToORMAbstractionBridge.ORMToORMAbstractionBridgeDomainModel), "Neumont.Tools.ORMToORMAbstractionBridge.GeneratedCode.ORMToORMAbstractionBridgeDomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Uniqueness", PropertyDisplayNameKey="Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint/UniquenessConstraint.PropertyDisplayName", Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("6d7dd635-6b8d-4ea7-a2a5-003ada32afd0")]
		public virtual global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint UniquenessConstraint
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint)DslModeling::DomainRoleInfo.GetRolePlayer(this, UniquenessConstraintDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, UniquenessConstraintDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access UniquenessConstraint of a Uniqueness
		/// <summary>
		/// Gets UniquenessConstraint.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint GetUniquenessConstraint(global::Neumont.Tools.ORMAbstraction.Uniqueness element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, UniquenessDomainRoleId) as global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint;
		}
		
		/// <summary>
		/// Sets UniquenessConstraint.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetUniquenessConstraint(global::Neumont.Tools.ORMAbstraction.Uniqueness element, global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint newUniquenessConstraint)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, UniquenessDomainRoleId, newUniquenessConstraint);
		}
		#endregion
		#region Uniqueness link accessor
		/// <summary>
		/// Get the UniquenessIsForUniquenessConstraint link to a Uniqueness.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint GetLinkToUniquenessConstraint (global::Neumont.Tools.ORMAbstraction.Uniqueness uniquenessInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint>(uniquenessInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.UniquenessDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Uniqueness not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region UniquenessConstraint link accessor
		/// <summary>
		/// Get the UniquenessIsForUniquenessConstraint link to a UniquenessConstraint.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint GetLinkToUniqueness (global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint uniquenessConstraintInstance)
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint>(uniquenessConstraintInstance, global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.UniquenessConstraintDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of UniquenessConstraint not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region UniquenessIsForUniquenessConstraint instance accessors
		
		/// <summary>
		/// Get any UniquenessIsForUniquenessConstraint links between a given Uniqueness and a UniquenessConstraint.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint> GetLinks( global::Neumont.Tools.ORMAbstraction.Uniqueness source, global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint target )
		{
			global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint> outLinks = new global::System.Collections.Generic.List<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint>();
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.UniquenessDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint link in links )
			{
				if ( target.Equals(link.UniquenessConstraint) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one UniquenessIsForUniquenessConstraint link between a given Uniquenessand a UniquenessConstraint.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint GetLink( global::Neumont.Tools.ORMAbstraction.Uniqueness source, global::Neumont.Tools.ORM.ObjectModel.UniquenessConstraint target )
		{
			global::System.Collections.Generic.IList<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint>(source, global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint.UniquenessDomainRoleId);
			foreach ( global::Neumont.Tools.ORMToORMAbstractionBridge.UniquenessIsForUniquenessConstraint link in links )
			{
				if ( target.Equals(link.UniquenessConstraint) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
