::  This file was generated by VersionGenerator.exe. It should NOT be directly modified. 
@SET ProductMajorVersion=1
@SET ProductMinorVersion=0
@SET ProductBuildVersion=1509
@SET ProductRevisionVersion=8982
