<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" 
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
	xmlns:oil="http://schemas.orm.net/OIAL" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:exsl="http://exslt.org/common"
	xmlns:odt="http://schemas.orm.net/ORMDataTypes"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	extension-element-prefixes="exsl"
	exclude-result-prefixes="oil odt">
	<xsl:import href="OIALtoXSD.xslt"/>

	<xsl:output method="xml" encoding="utf-8" media-type="text/xml" indent="yes"/>
	<xsl:strip-space elements="*"/>
	<xsl:template match="/">
		<xsl:apply-templates select="*"/>
	</xsl:template>
	<!--TODO: finnish abstraction layer for finding common xml schema types. To be shared with XSD generation and OWL and XFORMS
		TODO: finnish abstraction layer for dealing with relational structures and corcular references. This applies to WSDL, XSD, and the relational generation and possibly more generation mechanisims.
		TODO: allign this generation with another layer of generation(possibly Object Model or just another generation schema for accessing data directly through a DAL.-->
	<xsl:template match="oil:model">
		<xsl:comment>THIS WSDL WAS GENERATED BY THE ORM2 TOOL</xsl:comment>
		<!-- UNDONE: Do other stuff related to the namespaces-->
		<wsdl:definitions name="FooSample" targetNamespace="" xmlns:wsdlns="urn:" xmlns:typens="http://tempuri.org/xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:stk="http://schemas.microsoft.com/soap-toolkit/wsdl-extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
			<wsdl:types>
				<xsl:apply-imports/>
			</wsdl:types>
			<xsl:call-template name="GenerateMessages"/>
			<xsl:call-template name="GeneratePortType"/>
			<xsl:call-template name="GenerateBinding"/>
		</wsdl:definitions>
	</xsl:template>
	<xsl:template name="GenerateMessages">
	
	</xsl:template>
	<xsl:template name="GeneratePortType">
		
	</xsl:template>
	<xsl:template name="GenerateBinding">
		
	</xsl:template>
</xsl:stylesheet>