//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northface.Tools.ORM.ShapeModel
{
    using System;
    using System.Reflection;
    
    /// <summary>
    ///</summary>
    public partial class ORMShapeModel
    {
        /// <summary>
        ///</summary>
        protected override Type[] AllMetaModelTypes()
        {
            return new Type[] {
                    typeof(ExternalConstraintShape).GetNestedType("ShapeChangeRule", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(FactTypeShape).GetNestedType("ConstraintDisplayPositionChangeRule", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(FactTypeShape).GetNestedType("ExternalConstraintShapeChangeRule", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(FactTypeShape).GetNestedType("SwitchFromNestedFact", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(FactTypeShape).GetNestedType("SwitchToNestedFact", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(FrequencyConstraintShape).GetNestedType("FrequencyConstraintAttributeChangeRule", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ObjectTypeShape).GetNestedType("PreferredIdentifierRemovedRule", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ObjectTypeShape).GetNestedType("ShapeChangeRule", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ConstraintRoleSequenceRoleAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ConstraintRoleSequenceRoleRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ExternalFactConstraintAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ExternalFactConstraintRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("FactTypedAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("FactTypeHasInternalConstraintAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("FactTypeHasInternalConstraintRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("MultiColumnExternalConstraintAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ObjectTypedAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ObjectTypePlaysRoleRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ObjectTypeShapeChangeRule", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("PresentationLinkRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("PrimaryIdentifierAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("PrimaryIdentifierRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("RoleAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("RolePlayerAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("RoleRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("RoleValueRangeDefinitionAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("RoleValueRangeDefinitionRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("SingleColumnExternalConstraintAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ValueTypeValueRangeDefinitionAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ORMDiagram).GetNestedType("ValueTypeValueRangeDefinitionRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ReadingShape).GetNestedType("ReadingOrderAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ReadingShape).GetNestedType("ReadingOrderReadingTextChanged", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ReadingShape).GetNestedType("ReadingOrderRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ReadingShape).GetNestedType("ReadingTextChanged", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(RolePlayerLink).GetNestedType("InternalConstraintRoleSequenceAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(RolePlayerLink).GetNestedType("InternalConstraintRoleSequenceRoleRemoved", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(RolePlayerLink).GetNestedType("RolePlayerRemoving", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ValueRangeShape).GetNestedType("ValueRangeChanged", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ValueRangeShape).GetNestedType("ValueRangeDefinitionAdded", (BindingFlags.Public | BindingFlags.NonPublic)),
                    typeof(ValueRangeShape).GetNestedType("ValueTypeHasDataTypeAdded", (BindingFlags.Public | BindingFlags.NonPublic))};
        }
    }
}
