CREATE SCHEMA BlogDemo;

SET SCHEMA 'BLOGDEMO';

CREATE TABLE BlogDemo.BlogEntry
(
	BlogEntry_Id INTEGER NOT NULL,
	EntryTitle CHARACTER VARYING(30) NOT NULL,
	EntryBody CHARACTER LARGE OBJECT() NOT NULL,
	PostedDate TIMESTAMP NOT NULL,
	UserIdName2 CHARACTER VARYING(30) NOT NULL,
	UserIdName1 CHARACTER VARYING(30) NOT NULL,
	BlogCommentParentEntryId INTEGER,
	CONSTRAINT InternalUniquenessConstraint1 PRIMARY KEY(BlogEntry_Id)
);

CREATE TABLE BlogDemo."User"
(
	Name1 CHARACTER VARYING(30) NOT NULL,
	Name2 CHARACTER VARYING(30) NOT NULL,
	Username CHARACTER VARYING(30) NOT NULL,
	Password CHARACTER(32) NOT NULL,
	CONSTRAINT ExternalUniquenessConstraint1 PRIMARY KEY(Name1, Name2)
);

CREATE TABLE BlogDemo.BlogLabel
(
	BlogLabel_Id INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	Title CHARACTER LARGE OBJECT(),
	CONSTRAINT InternalUniquenessConstraint18 PRIMARY KEY(BlogLabel_Id)
);

CREATE TABLE BlogDemo.BlogEntryLabel
(
	BlogEntryId INTEGER NOT NULL,
	BlogLabelId INTEGER NOT NULL,
	CONSTRAINT InternalUniquenessConstraint20 PRIMARY KEY(BlogEntryId, BlogLabelId)
);

ALTER TABLE BlogDemo.BlogEntry ADD CONSTRAINT BlogEntry_FK1 FOREIGN KEY (UserIdName2, UserIdName1) REFERENCES BlogDemo."User" (Name1, Name2) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BlogDemo.BlogEntry ADD CONSTRAINT BlogEntry_FK2 FOREIGN KEY (BlogCommentParentEntryId) REFERENCES BlogDemo.BlogEntry (BlogEntry_Id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BlogDemo.BlogEntryLabel ADD CONSTRAINT BlogEntryLabel_FK1 FOREIGN KEY (BlogEntryId) REFERENCES BlogDemo.BlogEntry (BlogEntry_Id) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BlogDemo.BlogEntryLabel ADD CONSTRAINT BlogEntryLabel_FK2 FOREIGN KEY (BlogLabelId) REFERENCES BlogDemo.BlogLabel (BlogLabel_Id) ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT;

