BEGIN TRANSACTION;
GO

CREATE SCHEMA PersonCountryDemo;
GO

CREATE TABLE PersonCountryDemo.Person
(
	Person_id BIGINT IDENTITY (1, 1) NOT NULL, 
	LastName NATIONAL CHARACTER VARYING(30) NOT NULL, 
	FirstName NATIONAL CHARACTER VARYING(30) NOT NULL, 
	Title NATIONAL CHARACTER VARYING(4) CONSTRAINT Title_Chk CHECK (Title IN ('Dr', 'Prof', 'Mr', 'Mrs', 'Miss', 'Ms')) , 
	Cntry_Cntry_nm NATIONAL CHARACTER VARYING(20) , 
	INSERT_DATE DATE NOT NULL, 
	UPDATE_DATE DATE , 
	ERROR_FLAG_IND FLOAT , 
	SOURCE_SYSTEM_CD NATIONAL CHARACTER VARYING(10) NOT NULL, 
	STUDY_SHORT_NAME NATIONAL CHARACTER VARYING(20) , 
	CONSTRAINT IUC1 PRIMARY KEY(Person_id)
);

CREATE TABLE PersonCountryDemo.Country
(
	Country_name NATIONAL CHARACTER VARYING(20) NOT NULL, 
	Region_Region_code NATIONAL CHARACTER(8) CONSTRAINT Region_code_Chk CHECK ((LEN(LTRIM(RTRIM(Region_Region_code)))) >= 8) , 
	INSERT_DATE DATE NOT NULL, 
	UPDATE_DATE DATE , 
	ERROR_FLAG_IND FLOAT , 
	SOURCE_SYSTEM_CD NATIONAL CHARACTER VARYING(10) NOT NULL, 
	STUDY_SHORT_NAME NATIONAL CHARACTER VARYING(20) , 
	CONSTRAINT IUC3 PRIMARY KEY(Country_name)
);

ALTER TABLE PersonCountryDemo.Person ADD CONSTRAINT Person_Country_FK FOREIGN KEY (Cntry_Cntry_nm)  REFERENCES PersonCountryDemo.Country (Country_name)  ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT WORK;

