START TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ WRITE;

CREATE SCHEMA PersonCountryDemo DEFAULT CHARACTER SET UTF8;

SET SCHEMA 'PERSONCOUNTRYDEMO';

CREATE DOMAIN PersonCountryDemo.Title AS CHARACTER VARYING(4) CONSTRAINT Title_Chk CHECK (VALUE IN ('Dr', 'Prof', 'Mr', 'Mrs', 'Miss', 'Ms')) ;

CREATE DOMAIN PersonCountryDemo.Region_code AS CHARACTER(8) CONSTRAINT Region_code_Chk CHECK ((CHARACTER_LENGTH(TRIM(BOTH FROM VALUE))) >= 8) ;

CREATE TABLE PersonCountryDemo.Person
(
	Person_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL, 
	LastName CHARACTER VARYING(30) NOT NULL, 
	FirstName CHARACTER VARYING(30) NOT NULL, 
	Title PersonCountryDemo.Title , 
	Cntry_Cntry_nm CHARACTER VARYING(20) , 
	INSERT_DATE DATE NOT NULL, 
	UPDATE_DATE DATE , 
	ERROR_FLAG_IND FLOAT , 
	SOURCE_SYSTEM_CD CHARACTER VARYING(10) NOT NULL, 
	STUDY_SHORT_NAME CHARACTER VARYING(20) , 
	CONSTRAINT IUC1 PRIMARY KEY(Person_id)
);

CREATE TABLE PersonCountryDemo.Country
(
	Country_name CHARACTER VARYING(20) NOT NULL, 
	Region_Region_code PersonCountryDemo.Region_code , 
	INSERT_DATE DATE NOT NULL, 
	UPDATE_DATE DATE , 
	ERROR_FLAG_IND FLOAT , 
	SOURCE_SYSTEM_CD CHARACTER VARYING(10) NOT NULL, 
	STUDY_SHORT_NAME CHARACTER VARYING(20) , 
	CONSTRAINT IUC3 PRIMARY KEY(Country_name)
);

ALTER TABLE PersonCountryDemo.Person ADD CONSTRAINT Country_FK FOREIGN KEY (Cntry_Cntry_nm)  REFERENCES PersonCountryDemo.Country (Country_name)  ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT WORK;

