CREATE SCHEMA SampleModel DEFAULT CHARACTER SET UTF8

	CREATE DOMAIN "Integer" AS BIGINT CONSTRAINT Integer_Chk CHECK(VALUE BETWEEN 1 AND 7) INITIALLY IMMEDIATE NOT DEFERRABLE
	CREATE DOMAIN Gender_Code AS CHARACTER(1) CONSTRAINT Gender_Code_Chk CHECK((CHARACTER_LENGTH(VALUE USING CHARACTERS)) >= 1 AND VALUE IN('M', 'F')) INITIALLY IMMEDIATE NOT DEFERRABLE


	CREATE TABLE PersonDrivesCar
	(
		DrivesCar_vin BIGINT
		DrvnByPrsn_Prsn_d BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
	)

	CREATE TABLE PBCFPOD
	(
		CarSold_vin BIGINT
		SaleDate_ymd BIGINT
		Buyer_Person_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
		Seller_Person_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
	)

	CREATE TABLE Review
	(
		Car_vin BIGINT
		Rating_Nr_Integer 
		Criteria_Name CHARACTER VARYING(10)
	)

	CREATE TABLE PersonHasNickName
	(
		NickName CHARACTER VARYING(10)
		Person_Person_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
	)

	CREATE TABLE Person
	(
		FirstName CHARACTER VARYING(10)
		Person_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
		Date_ymd BIGINT
		LastName CHARACTER VARYING(10)
		SclScrtyNmbr CHARACTER VARYING(10)
		HatType_ColorARGB BIGINT
		HTHTSHTSD CHARACTER VARYING(10)
		OwnsCar_vin BIGINT
		Gender_Gender_Code 
		VlTyp1_VlTyp1Vl BIGINT
	)

	CREATE TABLE Task
	(
		Task_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
		Person_Person_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
	)

	CREATE TABLE ValueType1
	(
		ValueType1Value BIGINT
		Person_Person_id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)
	)