CREATE SCHEMA CatalName.SchemaNameAttr AUTHORIZATION AuthIdenti DEFAULT CHARACTER SET UTF8 PATH CatalName.SchemaNameAtt, SecondCatName.SecondSchemaName
	CREATE GLOBAL TEMPORARY TABLE catalogAtt.SchemaNameAtt.nameAtt
	(
		boolName BOOLEAN DEFAULT INTERVAL '2005-12' DAY TO MINUTE
		boolName2 BINARY LARGE OBJECT(8)
		charStrName CHARACTER VARYING(8) CHARACTER SET UTF8
		numName INTERVAL YEAR TO MONTH(4) DEFAULT TIMESTAMP '2005-12-09 17:07:00'
		aprxNumName FLOAT(9)
		binStrName TIME(10) WITH TIME ZONE
		dateNameVar DATE
	)