/* This file was generated by VersionGenerator.exe. It should NOT be directly modified. */
[assembly: System.Reflection.AssemblyFileVersion("1.0.1305.1812")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.1305.1812 2013-05CTP")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Resources.SatelliteContractVersion("1.0.0.0")]
